import Head from 'next/head'
import { useEffect, useState } from 'react'
import axios from 'axios';
import styles from '../styles/Home.module.css'

export default function Home() {
  const [profile, setProfile] = useState(null);

  useEffect(() => {
    const init = async () => {
      const Keycloak = (await import('keycloak-js')).default;
      const keycloak = Keycloak({
        url: 'https://keycloak.pingpu.org/auth/',
        realm: 'master',
        clientId: 'todo',
      });
      const authenticated = await keycloak.init({ onLoad: 'login-required' });
      if (!authenticated) {
        console.error('login failed');
      } else {
        setProfile(keycloak.tokenParsed);
        axios.defaults.headers.Authorization = `Bearer ${keycloak.token}`;

        const remoteProfile = await axios.get('/api/profile');
        console.log(remoteProfile);
      }
    };
    init();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {!profile ? <main className={styles.main}>
        正在登录...
      </main> : <main className={styles.main}>
        <div>欢迎，{profile.preferred_username}</div>
      </main>}
    </div>
  )
}
